#!/bin/sh
# fbpath_retrain.sh - Retrain the freebase paths classifier from scratch
#
# Usage: fbpath_retrain.sh DATADIR
# Example: data/ml/fbpath-emb/fbpath_retrain.sh ../dataset-factoid-webquestions/
#
# Requires dataset-factoid-webquestions checkout and Sentence-selection checkout.
# Requires all relation generated by generate_relations.py script in data/ml/fbpath-emb/relations

set -e

datadir=$1

# First stage - training Mb concept matrix

rm -rf data/ml/fbpath-emb/props-webquestions-train
mkdir data/ml/fbpath-emb/props-webquestions-train
data/ml/fbpath-emb/fbpath_emb.py "$datadir"/d-dump/trainmodel.json data/ml/fbpath-emb/relations/trainmodel.json "$datadir"/d-freebase-brp/trainmodel.json data/ml/fbpath-emb/props-webquestions-train

basedir=$(pwd)
cd ../Sentence-selection/
./std_run.sh -p "$basedir"/data/ml/fbpath-emb/props-webquestions-train
cp data/Mbtemp.txt ../yodaqa/src/main/resources/cz/brmlab/yodaqa/analysis/question/Mbrel1.txt
cd "$basedir"
